// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class AppDbContext : DbContext
{
    public AppDbContext()
    {
    }

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<AnalyzeActivity> AnalyzeActivities { get; set; }

    public virtual DbSet<AnalyzeOneBook> AnalyzeOneBooks { get; set; }

    public virtual DbSet<AnalyzeSale> AnalyzeSales { get; set; }

    public virtual DbSet<AnalyzeUserInteraction> AnalyzeUserInteractions { get; set; }

    public virtual DbSet<Article> Articles { get; set; }

    public virtual DbSet<Book> Books { get; set; }

    public virtual DbSet<BookPreview> BookPreviews { get; set; }

    public virtual DbSet<BookProduct> BookProducts { get; set; }

    public virtual DbSet<BookReview> BookReviews { get; set; }

    public virtual DbSet<Bookseller> Booksellers { get; set; }

    public virtual DbSet<Cart> Carts { get; set; }

    public virtual DbSet<CartDetail> CartDetails { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Category1> Categories1 { get; set; }

    public virtual DbSet<Comment> Comments { get; set; }

    public virtual DbSet<Coupon> Coupons { get; set; }

    public virtual DbSet<CouponRedemption> CouponRedemptions { get; set; }

    public virtual DbSet<CouponType> CouponTypes { get; set; }

    public virtual DbSet<EBook> EBooks { get; set; }

    public virtual DbSet<EBooksPermission> EBooksPermissions { get; set; }

    public virtual DbSet<EcpayOrder> EcpayOrders { get; set; }

    public virtual DbSet<Employee> Employees { get; set; }

    public virtual DbSet<Favorite> Favorites { get; set; }

    public virtual DbSet<GroupFunction> GroupFunctions { get; set; }

    public virtual DbSet<GroupPermission> GroupPermissions { get; set; }

    public virtual DbSet<Keyword> Keywords { get; set; }

    public virtual DbSet<LogisticsOrder> LogisticsOrders { get; set; }

    public virtual DbSet<Member> Members { get; set; }

    public virtual DbSet<MyCache> MyCaches { get; set; }

    public virtual DbSet<News> News { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrderDetail> OrderDetails { get; set; }

    public virtual DbSet<PdInStock> PdInStocks { get; set; }

    public virtual DbSet<PointsHistory> PointsHistories { get; set; }

    public virtual DbSet<Post> Posts { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductDetailsCategory> ProductDetailsCategorys { get; set; }

    public virtual DbSet<ProductKeyword> ProductKeywords { get; set; }

    public virtual DbSet<ProductPicture> ProductPictures { get; set; }

    public virtual DbSet<Promotion> Promotions { get; set; }

    public virtual DbSet<PromotionEvent> PromotionEvents { get; set; }

    public virtual DbSet<QtyBookInventory> QtyBookInventories { get; set; }

    public virtual DbSet<QtyflawBook> QtyflawBooks { get; set; }

    public virtual DbSet<Refund> Refunds { get; set; }

    public virtual DbSet<Return> Returns { get; set; }

    public virtual DbSet<Tag> Tags { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<UsedBook> UsedBooks { get; set; }

    public virtual DbSet<UsedBookBuyerInformation> UsedBookBuyerInformations { get; set; }

    public virtual DbSet<UsedBookOrderMessage> UsedBookOrderMessages { get; set; }

    public virtual DbSet<UsedBookPaymentRecord> UsedBookPaymentRecords { get; set; }

    public virtual DbSet<UsedBooksAllocationRecord> UsedBooksAllocationRecords { get; set; }

    public virtual DbSet<UsedBooksCart> UsedBooksCarts { get; set; }

    public virtual DbSet<UsedBooksLogisticsOrder> UsedBooksLogisticsOrders { get; set; }

    public virtual DbSet<UsedBooksOrder> UsedBooksOrders { get; set; }

    public virtual DbSet<UsedBooksOrderDetail> UsedBooksOrderDetails { get; set; }

    public virtual DbSet<UsedBooksReturn> UsedBooksReturns { get; set; }

    public virtual DbSet<WriteBookReview> WriteBookReviews { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=fuen31-t3.database.windows.net;Initial Catalog=ProjectDB;User ID=zlk;Password=fuen31t3!");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("Chinese_Taiwan_Stroke_CI_AS_KS_WS");

        modelBuilder.Entity<AnalyzeActivity>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_ActivityResults");
        });

        modelBuilder.Entity<AnalyzeOneBook>(entity =>
        {
            entity.HasOne(d => d.Book).WithMany(p => p.AnalyzeOneBooks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AnalyzeOneBook_Products");
        });

        modelBuilder.Entity<AnalyzeSale>(entity =>
        {
            entity.HasOne(d => d.Book).WithMany(p => p.AnalyzeSales)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AnalyzeSales_Products");
        });

        modelBuilder.Entity<AnalyzeUserInteraction>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_UserInteractions");

            entity.HasOne(d => d.Book).WithMany(p => p.AnalyzeUserInteractions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AnalyzeUserInteractions_Products");

            entity.HasOne(d => d.Member).WithMany(p => p.AnalyzeUserInteractions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_AnalyzeUserInteractions_Members");
        });

        modelBuilder.Entity<Article>(entity =>
        {
            entity.HasKey(e => e.ArticleID).HasName("PK__tmp_ms_x__9C6270C8E33FD3BA");

            entity.Property(e => e.EmployeeID).HasDefaultValueSql("((7))");
            entity.Property(e => e.PublishTime).HasDefaultValueSql("('2024/02/06 14:00')");
            entity.Property(e => e.Title).HasDefaultValueSql("(N'這是預設內容')");

            entity.HasOne(d => d.Employee).WithMany(p => p.Articles).HasConstraintName("FK__Articles__Employ__078C1F06");
        });

        modelBuilder.Entity<Book>(entity =>
        {
            entity.HasOne(d => d.Category).WithMany(p => p.Books)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Books_Categories");
        });

        modelBuilder.Entity<BookPreview>(entity =>
        {
            entity.HasOne(d => d.Book).WithMany(p => p.BookPreviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookPreviews_Books");
        });

        modelBuilder.Entity<BookProduct>(entity =>
        {
            entity.HasOne(d => d.Book).WithMany(p => p.BookProducts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookProducts_Books");

            entity.HasOne(d => d.Product).WithMany(p => p.BookProducts).HasConstraintName("FK_BookProducts_Products");

            entity.HasOne(d => d.Publisher).WithMany(p => p.BookProducts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_BookProducts_Booksellers");
        });

        modelBuilder.Entity<BookReview>(entity =>
        {
            entity.HasKey(e => e.ReviewID).HasName("PK__BookRevi__74BC79AE03C21AA2");

            entity.Property(e => e.ReviewID).ValueGeneratedNever();
            entity.Property(e => e.Rating).IsFixedLength();

            entity.HasOne(d => d.Member).WithMany(p => p.BookReviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BookRevie__Membe__0D44F85C");
        });

        modelBuilder.Entity<Bookseller>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_DepositHistory");

            entity.Property(e => e.ID).ValueGeneratedNever();
        });

        modelBuilder.Entity<Cart>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Carts_1");

            entity.HasOne(d => d.Member).WithOne(p => p.Cart)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Carts_Members");
        });

        modelBuilder.Entity<CartDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_CartItem");

            entity.HasOne(d => d.Cart).WithMany(p => p.CartDetails).HasConstraintName("FK_CartDetail_Carts");

            entity.HasOne(d => d.Product).WithMany(p => p.CartDetails).HasConstraintName("FK_CartDetail_Products");
        });

        modelBuilder.Entity<Comment>(entity =>
        {
            entity.HasOne(d => d.Employee).WithMany(p => p.Comments).HasConstraintName("FK_Comments_Employees");

            entity.HasOne(d => d.Post).WithMany(p => p.Comments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Comments_Posts");

            entity.HasOne(d => d.User).WithMany(p => p.Comments).HasConstraintName("FK_Comments_Members");
        });

        modelBuilder.Entity<Coupon>(entity =>
        {
            entity.HasKey(e => e.CouponID).HasName("PK__Coupons__384AF1DA6EFC472C");

            entity.Property(e => e.AvailabilityCount).HasDefaultValueSql("((100))");
            entity.Property(e => e.CouponTypeId).HasDefaultValueSql("((1))");
            entity.Property(e => e.DiscountValue).HasDefaultValueSql("((10))");
            entity.Property(e => e.PromotionID).HasDefaultValueSql("((1))");
            entity.Property(e => e.Valid).HasDefaultValueSql("((1))");

            entity.HasOne(d => d.CouponType).WithMany(p => p.Coupons)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Coupons_CouponTypes");
        });

        modelBuilder.Entity<CouponRedemption>(entity =>
        {
            entity.HasKey(e => e.UsageID).HasName("PK__CouponRe__29B197C04755808C");

            entity.HasOne(d => d.Coupon).WithMany(p => p.CouponRedemptions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CouponRed__Coupo__0B5CAFEA");
        });

        modelBuilder.Entity<CouponType>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__CouponTy__3214EC07289353B6");
        });

        modelBuilder.Entity<EBook>(entity =>
        {
            entity.HasOne(d => d.Product).WithMany(p => p.EBooks).HasConstraintName("FK_Products_EBooks");
        });

        modelBuilder.Entity<EBooksPermission>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_EBooks.Permissions");

            entity.Property(e => e.CreateDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Book).WithMany(p => p.EBooksPermissions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EBooksPermissions_EBooks");

            entity.HasOne(d => d.Member).WithMany(p => p.EBooksPermissions)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_EBooksPermissions_Members");
        });

        modelBuilder.Entity<Employee>(entity =>
        {
            entity.HasOne(d => d.Group).WithMany(p => p.Employees)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Employees_GroupPermission");
        });

        modelBuilder.Entity<Favorite>(entity =>
        {
            entity.HasKey(e => e.FavoriteID).HasName("PK__Favorite__CE74FAF5752B63A5");

            entity.HasOne(d => d.Member).WithMany(p => p.Favorites).HasConstraintName("FK__Favorites__Membe__43A1090D");
        });

        modelBuilder.Entity<GroupFunction>(entity =>
        {
            entity.HasMany(d => d.Groups).WithMany(p => p.Functions)
                .UsingEntity<Dictionary<string, object>>(
                    "GroupRelationship",
                    r => r.HasOne<GroupPermission>().WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_GroupRelationship_GroupPermission"),
                    l => l.HasOne<GroupFunction>().WithMany()
                        .HasForeignKey("FunctionId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_GroupRelationship_GroupFunction"),
                    j =>
                    {
                        j.HasKey("FunctionId", "GroupId").HasName("PK__GroupRel__80E255CEFD8DC8B1");
                        j.ToTable("GroupRelationship");
                    });
        });

        modelBuilder.Entity<LogisticsOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_LogisticsOreder");

            entity.HasOne(d => d.Order).WithMany(p => p.LogisticsOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_LogisticsOreder_Orders");
        });

        modelBuilder.Entity<Member>(entity =>
        {
            entity.Property(e => e.CreatedAt).HasDefaultValueSql("(getutcdate())");
        });

        modelBuilder.Entity<MyCache>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__MyCache__3214EC076DB8598B");

            entity.Property(e => e.Id).UseCollation("SQL_Latin1_General_CP1_CS_AS");
        });

        modelBuilder.Entity<News>(entity =>
        {
            entity.HasKey(e => e.NewsID).HasName("PK__tmp_ms_x__954EBDD33D0CF578");

            entity.HasOne(d => d.Employee).WithMany(p => p.News)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__News__EmployeeID__0A688BB1");
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_PhysicalBookOrders");

            entity.Property(e => e.Phone).IsFixedLength();

            entity.HasOne(d => d.Member).WithMany(p => p.Orders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Orders_Members");
        });

        modelBuilder.Entity<OrderDetail>(entity =>
        {
            entity.HasOne(d => d.Order).WithMany(p => p.OrderDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDetails_Orders");

            entity.HasOne(d => d.Product).WithMany(p => p.OrderDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_OrderDetails_Products");
        });

        modelBuilder.Entity<PdInStock>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_InStock");

            entity.HasOne(d => d.Product).WithMany(p => p.PdInStocks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PdInStock_Products");

            entity.HasOne(d => d.Supplier).WithMany(p => p.PdInStocks).HasConstraintName("FK_PdInStock_Bookseller");
        });

        modelBuilder.Entity<PointsHistory>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Member).WithMany(p => p.PointsHistories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_PointsHistory_Members");
        });

        modelBuilder.Entity<Post>(entity =>
        {
            entity.HasOne(d => d.Author).WithMany(p => p.Posts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Posts_Employees");

            entity.HasMany(d => d.Categories).WithMany(p => p.Posts)
                .UsingEntity<Dictionary<string, object>>(
                    "PostCategory",
                    r => r.HasOne<Category1>().WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PostCategories_Categories"),
                    l => l.HasOne<Post>().WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PostCategories_Posts"),
                    j =>
                    {
                        j.HasKey("PostId", "CategoryId");
                        j.ToTable("PostCategories");
                    });

            entity.HasMany(d => d.Tags).WithMany(p => p.Posts)
                .UsingEntity<Dictionary<string, object>>(
                    "PostTag",
                    r => r.HasOne<Tag>().WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PostTags_Tags"),
                    l => l.HasOne<Post>().WithMany()
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("FK_PostTags_Posts"),
                    j =>
                    {
                        j.HasKey("PostId", "TagId");
                        j.ToTable("PostTags");
                    });
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.ToTable(tb => tb.HasTrigger("tr_Products_UpdateDiscountDegree"));

            entity.Property(e => e.RealPrice).HasComputedColumnSql("([Price]-([Price]*[DiscountDegree])/(100))", false);

            entity.HasOne(d => d.DetailsCategory).WithMany(p => p.Products).HasConstraintName("FK_Products_ProductDetailsCategorys");
        });

        modelBuilder.Entity<ProductKeyword>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_BookKeywords");

            entity.HasOne(d => d.Keyword).WithMany(p => p.ProductKeywords).HasConstraintName("FK_ProductKeywords_Keywords");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductKeywords).HasConstraintName("FK_ProductKeywords_ProductKeywords");
        });

        modelBuilder.Entity<ProductPicture>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_Pictures");

            entity.HasOne(d => d.Product).WithMany(p => p.ProductPictures).HasConstraintName("FK_ProductPictures_Products");
        });

        modelBuilder.Entity<Promotion>(entity =>
        {
            entity.HasKey(e => e.PromotionID).HasName("PK__Promotio__52C42F2FFEA38B1F");
        });

        modelBuilder.Entity<PromotionEvent>(entity =>
        {
            entity.HasKey(e => e.EventID).HasName("PK__Promotio__7944C8709C67447C");

            entity.Property(e => e.DiscountRate).HasDefaultValueSql("((1))");
            entity.Property(e => e.EventSerialNumber).HasDefaultValueSql("(N'EventCode')");
            entity.Property(e => e.OfferStatus).HasDefaultValueSql("(N'未啟用')");
            entity.Property(e => e.StartDate).HasDefaultValueSql("(((2024)/(2))/(6))");
        });

        modelBuilder.Entity<QtyBookInventory>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_BookInventory");

            entity.HasOne(d => d.Product).WithMany(p => p.QtyBookInventories)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QtyBookInventories_Products");
        });

        modelBuilder.Entity<QtyflawBook>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_DefectiveItems");

            entity.HasOne(d => d.Book).WithMany(p => p.QtyflawBooks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_QtyflawBooks_Products");
        });

        modelBuilder.Entity<Refund>(entity =>
        {
            entity.HasOne(d => d.Order).WithMany(p => p.Refunds)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Refund_Orders");
        });

        modelBuilder.Entity<Return>(entity =>
        {
            entity.HasOne(d => d.LogisticsOrder).WithMany(p => p.Returns)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Return_LogisticsOreder");

            entity.HasOne(d => d.Member).WithMany(p => p.Returns)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Return_Members");

            entity.HasOne(d => d.Order).WithMany(p => p.Returns)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Return_Orders");
        });

        modelBuilder.Entity<UsedBook>(entity =>
        {
            entity.HasOne(d => d.Category).WithMany(p => p.UsedBooks).HasConstraintName("FK_UsedBooks_Categories");

            entity.HasOne(d => d.Member).WithMany(p => p.UsedBooks)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsedBooks_Members");
        });

        modelBuilder.Entity<UsedBookOrderMessage>(entity =>
        {
            entity.Property(e => e.DateTime).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<UsedBooksAllocationRecord>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_UsedBooks.AllocationRecords");

            entity.Property(e => e.Id).ValueGeneratedNever();

            entity.HasOne(d => d.Member).WithMany(p => p.UsedBooksAllocationRecords)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsedBooksAllocationRecords_Members");

            entity.HasOne(d => d.Order).WithMany(p => p.UsedBooksAllocationRecords)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsedBooksAllocationRecords_UsedBooksOrders");
        });

        modelBuilder.Entity<UsedBooksCart>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_UsedBooks.Cart");

            entity.Property(e => e.AddToCartDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Book).WithMany(p => p.UsedBooksCarts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsedBooksCart_UsedBooks");

            entity.HasOne(d => d.Member).WithMany(p => p.UsedBooksCarts)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsedBooksCart_Members");
        });

        modelBuilder.Entity<UsedBooksLogisticsOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_UsedBooksLogisticsOreder");

            entity.Property(e => e.LogisticsCompany).HasDefaultValueSql("((1))");
            entity.Property(e => e.PickupMethod).HasDefaultValueSql("((1))");

            entity.HasOne(d => d.Order).WithMany(p => p.UsedBooksLogisticsOrders)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsedBooksLogisticsOrder_UsedBooksOrders");
        });

        modelBuilder.Entity<UsedBooksOrder>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_UsedBooks.Orders");

            entity.Property(e => e.OrderDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Buyer).WithMany(p => p.UsedBooksOrderBuyers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsedBooksOrders_Members");

            entity.HasOne(d => d.Seller).WithMany(p => p.UsedBooksOrderSellers)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsedBooksOrders_Members1");
        });

        modelBuilder.Entity<UsedBooksOrderDetail>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK_UsedBooks.OrderDetails");

            entity.HasOne(d => d.Book).WithMany(p => p.UsedBooksOrderDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsedBooksOrderDetails_UsedBooks");

            entity.HasOne(d => d.Order).WithMany(p => p.UsedBooksOrderDetails)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsedBooksOrderDetails_UsedBooksOrders");
        });

        modelBuilder.Entity<UsedBooksReturn>(entity =>
        {
            entity.Property(e => e.ApplicationDate).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.Order).WithMany(p => p.UsedBooksReturns)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_UsedBooksReturn_UsedBooksOrders");
        });

        modelBuilder.Entity<WriteBookReview>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK_BookReviews");

            entity.HasOne(d => d.Book).WithMany(p => p.WriteBookReviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WriteBookReviews_Products");

            entity.HasOne(d => d.Member).WithMany(p => p.WriteBookReviews)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_WriteBookReviews_Members");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}