// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("BookProducts", Schema = "Books")]
public partial class BookProduct
{
    [Key]
    public int Id { get; set; }

    public int BookId { get; set; }

    public int ProductId { get; set; }

    public int PublisherId { get; set; }

    [Column(TypeName = "date")]
    public DateTime PublishDate { get; set; }

    [Required]
    [StringLength(13)]
    public string ISBN { get; set; }

    [ForeignKey("BookId")]
    [InverseProperty("BookProducts")]
    public virtual Book Book { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("BookProducts")]
    public virtual Product Product { get; set; }

    [ForeignKey("PublisherId")]
    [InverseProperty("BookProducts")]
    public virtual Bookseller Publisher { get; set; }
}