// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class BookPreview
{
    [Key]
    public int PreviewId { get; set; }

    public int BookId { get; set; }

    [StringLength(500)]
    public string PreviewURL { get; set; }

    public int? PreviewLength { get; set; }

    public string PreviewContent { get; set; }

    [StringLength(50)]
    public string PreviewType { get; set; }

    public bool? Available { get; set; }

    [ForeignKey("BookId")]
    [InverseProperty("BookPreviews")]
    public virtual Book Book { get; set; }
}