// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("Books", Schema = "Books")]
public partial class Book
{
    [Key]
    public int Id { get; set; }

    public int CategoryID { get; set; }

    [Required]
    [StringLength(50)]
    public string Author { get; set; }

    [Required]
    [StringLength(50)]
    public string Language { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("Book")]
    public virtual ICollection<BookPreview> BookPreviews { get; set; } = new List<BookPreview>();

    [InverseProperty("Book")]
    public virtual ICollection<BookProduct> BookProducts { get; set; } = new List<BookProduct>();

    [ForeignKey("CategoryID")]
    [InverseProperty("Books")]
    public virtual Category Category { get; set; }
}