// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("CartDetail", Schema = "Orders")]
public partial class CartDetail
{
    [Key]
    public int Id { get; set; }

    public int CartId { get; set; }

    public int? ProductId { get; set; }

    public int Quantity { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal UnitPrice { get; set; }

    [ForeignKey("CartId")]
    [InverseProperty("CartDetails")]
    public virtual Cart Cart { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("CartDetails")]
    public virtual Product Product { get; set; }
}