// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class Comment
{
    [Key]
    public int Id { get; set; }

    public int PostId { get; set; }

    public int? UserId { get; set; }

    public int? EmployeeId { get; set; }

    [Required]
    public string Content { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedDate { get; set; }

    [ForeignKey("EmployeeId")]
    [InverseProperty("Comments")]
    public virtual Employee Employee { get; set; }

    [ForeignKey("PostId")]
    [InverseProperty("Comments")]
    public virtual Post Post { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Comments")]
    public virtual Member User { get; set; }
}