// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("EBooks", Schema = "Books")]
public partial class EBook
{
    [Key]
    public int Id { get; set; }

    public int ProductId { get; set; }

    [Required]
    [StringLength(500)]
    public string FileLink { get; set; }

    [Required]
    [StringLength(500)]
    public string Sample { get; set; }

    [InverseProperty("Book")]
    public virtual ICollection<EBooksPermission> EBooksPermissions { get; set; } = new List<EBooksPermission>();

    [ForeignKey("ProductId")]
    [InverseProperty("EBooks")]
    public virtual Product Product { get; set; }
}