// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class EBooksPermission
{
    [Key]
    public int Id { get; set; }

    public int BookID { get; set; }

    public int MemberID { get; set; }

    public DateTime CreateDate { get; set; }

    [StringLength(50)]
    public string PermissionType { get; set; }

    [ForeignKey("BookID")]
    [InverseProperty("EBooksPermissions")]
    public virtual EBook Book { get; set; }

    [ForeignKey("MemberID")]
    [InverseProperty("EBooksPermissions")]
    public virtual Member Member { get; set; }
}