// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class Employee
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public bool Gender { get; set; }

    [Required]
    [StringLength(50)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    public string PhoneNumber { get; set; }

    [StringLength(50)]
    public string Position { get; set; }

    public int GroupId { get; set; }

    [Required]
    [StringLength(50)]
    public string Account { get; set; }

    [Required]
    [StringLength(50)]
    public string Password { get; set; }

    public bool EmailVerified { get; set; }

    [StringLength(6)]
    public string VerificationCode { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? VerificationCodeExpiration { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<Article> Articles { get; set; } = new List<Article>();

    [InverseProperty("Employee")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [ForeignKey("GroupId")]
    [InverseProperty("Employees")]
    public virtual GroupPermission Group { get; set; }

    [InverseProperty("Employee")]
    public virtual ICollection<News> News { get; set; } = new List<News>();

    [InverseProperty("Author")]
    public virtual ICollection<Post> Posts { get; set; } = new List<Post>();
}