// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class Favorite
{
    [Key]
    public int FavoriteID { get; set; }

    public int? MemberID { get; set; }

    public int? ItemID { get; set; }

    [ForeignKey("MemberID")]
    [InverseProperty("Favorites")]
    public virtual Member Member { get; set; }
}