// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("GroupPermission")]
public partial class GroupPermission
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string GroupName { get; set; }

    [InverseProperty("Group")]
    public virtual ICollection<Employee> Employees { get; set; } = new List<Employee>();

    [ForeignKey("GroupId")]
    [InverseProperty("Groups")]
    public virtual ICollection<GroupFunction> Functions { get; set; } = new List<GroupFunction>();
}