// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("LogisticsOrder", Schema = "Orders")]
public partial class LogisticsOrder
{
    [Key]
    public int Id { get; set; }

    public int OrderId { get; set; }

    [Required]
    [StringLength(50)]
    public string TrackingNumber { get; set; }

    public DateTime EstimatedDeliveryDate { get; set; }

    public DateTime ActualDeliveryDate { get; set; }

    [Required]
    [StringLength(50)]
    public string RecipientName { get; set; }

    [Required]
    [StringLength(50)]
    public string RecipientPhone { get; set; }

    [Required]
    [StringLength(50)]
    public string RecipientAddress { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("LogisticsOrders")]
    public virtual Order Order { get; set; }

    [InverseProperty("LogisticsOrder")]
    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();
}