// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class Member
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    public bool Gender { get; set; }

    [Column(TypeName = "date")]
    public DateTime DateOfBirth { get; set; }

    [Required]
    [StringLength(50)]
    public string Email { get; set; }

    [Required]
    [StringLength(50)]
    public string Password { get; set; }

    [Required]
    [StringLength(50)]
    public string MembersLevel { get; set; }

    [Required]
    [StringLength(50)]
    public string Address { get; set; }

    [Required]
    [StringLength(50)]
    public string PhoneNumber { get; set; }

    public int Points { get; set; }

    public bool EmailVerified { get; set; }

    [StringLength(6)]
    public string VerificationCode { get; set; }

    public int? VerificationCodeExpiration { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreatedAt { get; set; }

    [StringLength(256)]
    public string ResetToken { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? ResetTokenExpiration { get; set; }

    [InverseProperty("Member")]
    public virtual ICollection<AnalyzeUserInteraction> AnalyzeUserInteractions { get; set; } = new List<AnalyzeUserInteraction>();

    [InverseProperty("Member")]
    public virtual ICollection<BookReview> BookReviews { get; set; } = new List<BookReview>();

    [InverseProperty("Member")]
    public virtual Cart Cart { get; set; }

    [InverseProperty("User")]
    public virtual ICollection<Comment> Comments { get; set; } = new List<Comment>();

    [InverseProperty("Member")]
    public virtual ICollection<EBooksPermission> EBooksPermissions { get; set; } = new List<EBooksPermission>();

    [InverseProperty("Member")]
    public virtual ICollection<Favorite> Favorites { get; set; } = new List<Favorite>();

    [InverseProperty("Member")]
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    [InverseProperty("Member")]
    public virtual ICollection<PointsHistory> PointsHistories { get; set; } = new List<PointsHistory>();

    [InverseProperty("Member")]
    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();

    [InverseProperty("Member")]
    public virtual ICollection<UsedBook> UsedBooks { get; set; } = new List<UsedBook>();

    [InverseProperty("Member")]
    public virtual ICollection<UsedBooksAllocationRecord> UsedBooksAllocationRecords { get; set; } = new List<UsedBooksAllocationRecord>();

    [InverseProperty("Member")]
    public virtual ICollection<UsedBooksCart> UsedBooksCarts { get; set; } = new List<UsedBooksCart>();

    [InverseProperty("Buyer")]
    public virtual ICollection<UsedBooksOrder> UsedBooksOrderBuyers { get; set; } = new List<UsedBooksOrder>();

    [InverseProperty("Seller")]
    public virtual ICollection<UsedBooksOrder> UsedBooksOrderSellers { get; set; } = new List<UsedBooksOrder>();

    [InverseProperty("Member")]
    public virtual ICollection<WriteBookReview> WriteBookReviews { get; set; } = new List<WriteBookReview>();
}