// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class News
{
    [Key]
    [StringLength(50)]
    public string NewsID { get; set; }

    public int EmployeeID { get; set; }

    [Required]
    [StringLength(50)]
    public string Title { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime PublishTime { get; set; }

    [Required]
    public string Content { get; set; }

    [StringLength(50)]
    public string Category { get; set; }

    [ForeignKey("EmployeeID")]
    [InverseProperty("News")]
    public virtual Employee Employee { get; set; }
}