// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("Orders", Schema = "Orders")]
public partial class Order
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    [Required]
    [StringLength(50)]
    public string PaymentMethod { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime OrderDate { get; set; }

    public int TotalAmount { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    public int? DiscountAmount { get; set; }

    public string Message { get; set; }

    public string Address { get; set; }

    [StringLength(10)]
    public string Phone { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<LogisticsOrder> LogisticsOrders { get; set; } = new List<LogisticsOrder>();

    [ForeignKey("MemberId")]
    [InverseProperty("Orders")]
    public virtual Member Member { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    [InverseProperty("Order")]
    public virtual ICollection<Refund> Refunds { get; set; } = new List<Refund>();

    [InverseProperty("Order")]
    public virtual ICollection<Return> Returns { get; set; } = new List<Return>();
}