// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("PdInStock")]
public partial class PdInStock
{
    [Key]
    public int ID { get; set; }

    public int ProductId { get; set; }

    public int? SupplierID { get; set; }

    public int Qty { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime BuyDate { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal BuyPrice { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("PdInStocks")]
    public virtual Product Product { get; set; }

    [ForeignKey("SupplierID")]
    [InverseProperty("PdInStocks")]
    public virtual Bookseller Supplier { get; set; }
}