// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("PointsHistory")]
public partial class PointsHistory
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int PointChange { get; set; }

    [Required]
    [StringLength(50)]
    public string ChangeReason { get; set; }

    [Column(TypeName = "date")]
    public DateTime ChangeDate { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("PointsHistories")]
    public virtual Member Member { get; set; }
}