// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Index("ProductId", "KeywordId", Name = "ProductKeyword_unique", IsUnique = true)]
public partial class ProductKeyword
{
    [Key]
    public int Id { get; set; }

    public int ProductId { get; set; }

    public int KeywordId { get; set; }

    [ForeignKey("KeywordId")]
    [InverseProperty("ProductKeywords")]
    public virtual Keyword Keyword { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductKeywords")]
    public virtual Product Product { get; set; }
}