// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class QtyBookInventory
{
    [Key]
    public int Id { get; set; }

    public int ProductId { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal BuyPrice { get; set; }

    public int TotalQty { get; set; }

    [Required]
    [StringLength(50)]
    public string State { get; set; }

    public string Remark { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("QtyBookInventories")]
    public virtual Product Product { get; set; }
}