// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class QtyflawBook
{
    [Key]
    public int ID { get; set; }

    public int BookID { get; set; }

    [Required]
    [StringLength(100)]
    public string Reason { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime HandlingDate { get; set; }

    [Required]
    [StringLength(50)]
    public string HandlingMethod { get; set; }

    [Required]
    [StringLength(50)]
    public string Handler { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [ForeignKey("BookID")]
    [InverseProperty("QtyflawBooks")]
    public virtual Product Book { get; set; }
}