// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("Refund", Schema = "Orders")]
public partial class Refund
{
    [Key]
    public int Id { get; set; }

    public int OrderId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ApplicationDate { get; set; }

    public int Amount { get; set; }

    [Required]
    [StringLength(50)]
    public string RefundStatus { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Refunds")]
    public virtual Order Order { get; set; }
}