// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("Return", Schema = "Orders")]
public partial class Return
{
    [Key]
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int MemberId { get; set; }

    public int LogisticsOrderId { get; set; }

    public int Quantity { get; set; }

    [Required]
    [StringLength(50)]
    public string ReturnReason { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    [Column(TypeName = "date")]
    public DateTime ReturnDate { get; set; }

    [Column(TypeName = "date")]
    public DateTime ProcessdDate { get; set; }

    [ForeignKey("LogisticsOrderId")]
    [InverseProperty("Returns")]
    public virtual LogisticsOrder LogisticsOrder { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("Returns")]
    public virtual Member Member { get; set; }

    [ForeignKey("OrderId")]
    [InverseProperty("Returns")]
    public virtual Order Order { get; set; }
}