// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Keyless]
[Table("Transaction")]
public partial class Transaction
{
    public int Id { get; set; }

    public int OrderId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Date { get; set; }

    public int Amount { get; set; }

    [Required]
    [StringLength(50)]
    public string PaymentMethod { get; set; }
}