// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBooksOrder
{
    [Key]
    public int Id { get; set; }

    public int BuyerId { get; set; }

    public int SellerId { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime OrderDate { get; set; }

    public int TotalAmount { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    public int ShippingFee { get; set; }

    [StringLength(50)]
    public string PaymentMethod { get; set; }

    [ForeignKey("BuyerId")]
    [InverseProperty("UsedBooksOrderBuyers")]
    public virtual Member Buyer { get; set; }

    [ForeignKey("SellerId")]
    [InverseProperty("UsedBooksOrderSellers")]
    public virtual Member Seller { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<UsedBooksAllocationRecord> UsedBooksAllocationRecords { get; set; } = new List<UsedBooksAllocationRecord>();

    [InverseProperty("Order")]
    public virtual ICollection<UsedBooksLogisticsOrder> UsedBooksLogisticsOrders { get; set; } = new List<UsedBooksLogisticsOrder>();

    [InverseProperty("Order")]
    public virtual ICollection<UsedBooksOrderDetail> UsedBooksOrderDetails { get; set; } = new List<UsedBooksOrderDetail>();

    [InverseProperty("Order")]
    public virtual ICollection<UsedBooksReturn> UsedBooksReturns { get; set; } = new List<UsedBooksReturn>();
}