// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBookOrderMessage
{
    [Key]
    public int Id { get; set; }

    public int OrderId { get; set; }

    public int MemberId { get; set; }

    [Required]
    [StringLength(50)]
    public string Message { get; set; }

    public DateTime? DateTime { get; set; }
}