// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("UsedBooksReturn")]
public partial class UsedBooksReturn
{
    [Key]
    public int Id { get; set; }

    public int OrderID { get; set; }

    public int MemberID { get; set; }

    public DateTime ApplicationDate { get; set; }

    [Required]
    [StringLength(50)]
    public string ReturnReason { get; set; }

    [Required]
    [StringLength(50)]
    public string Status { get; set; }

    public DateTime? ProcessedDate { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("UsedBooksReturns")]
    public virtual UsedBooksOrder Order { get; set; }
}