// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("UsedBooksLogisticsOrder")]
public partial class UsedBooksLogisticsOrder
{
    [Key]
    public int Id { get; set; }

    public int OrderID { get; set; }

    [Required]
    [StringLength(50)]
    public string LogisticsCompany { get; set; }

    [Required]
    [StringLength(50)]
    public string TrackingNumber { get; set; }

    public DateTime EstimateDeliveryDate { get; set; }

    public DateTime? ActualDeliveryDate { get; set; }

    [Required]
    [StringLength(50)]
    public string PickupMethod { get; set; }

    [Required]
    [StringLength(50)]
    public string SenderAddress { get; set; }

    [Required]
    [StringLength(50)]
    public string SenderPhone { get; set; }

    [Required]
    [StringLength(50)]
    public string SenderName { get; set; }

    [Required]
    [StringLength(50)]
    public string RecipientName { get; set; }

    [Required]
    [StringLength(50)]
    public string RecipientPhone { get; set; }

    [Required]
    [StringLength(50)]
    public string RecipientAddress { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("UsedBooksLogisticsOrders")]
    public virtual UsedBooksOrder Order { get; set; }
}