// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBooksAllocationRecord
{
    [Key]
    public int Id { get; set; }

    public int OrderID { get; set; }

    public int MemberID { get; set; }

    [Required]
    [StringLength(50)]
    public string AllocationAccount { get; set; }

    public int AllocationAmount { get; set; }

    public int PlatformShareAmount { get; set; }

    [ForeignKey("MemberID")]
    [InverseProperty("UsedBooksAllocationRecords")]
    public virtual Member Member { get; set; }

    [ForeignKey("OrderID")]
    [InverseProperty("UsedBooksAllocationRecords")]
    public virtual UsedBooksOrder Order { get; set; }
}