// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class UsedBookPaymentRecord
{
    [Key]
    public int Id { get; set; }

    public int PaymentAmount { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string PaymentNumber { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string OrderId { get; set; }

    public bool status { get; set; }
}