// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("UsedBooks", Schema = "Books")]
public partial class UsedBook
{
    [Key]
    public int Id { get; set; }

    public int MemberId { get; set; }

    public int? CategoryId { get; set; }

    public bool ProductStatus { get; set; }

    [Required]
    [StringLength(50)]
    public string Name { get; set; }

    [StringLength(50)]
    public string Authors { get; set; }

    public string Description { get; set; }

    [StringLength(50)]
    public string PublisherName { get; set; }

    [Column(TypeName = "date")]
    public DateTime? PublishDate { get; set; }

    [Required]
    [StringLength(50)]
    public string ISBN { get; set; }

    [Column(TypeName = "decimal(18, 0)")]
    public decimal Price { get; set; }

    public byte[] Picture { get; set; }

    [Column(TypeName = "date")]
    public DateTime ReleaseDate { get; set; }

    [Required]
    [StringLength(500)]
    public string BookStatus { get; set; }

    public bool IsDeleted { get; set; }

    public string WebReaderLink { get; set; }

    [StringLength(500)]
    public string SmallThumbnailPicture { get; set; }

    [StringLength(500)]
    public string ThumbnailPicture { get; set; }

    [StringLength(500)]
    public string SmallPicture { get; set; }

    [ForeignKey("CategoryId")]
    [InverseProperty("UsedBooks")]
    public virtual Category Category { get; set; }

    [ForeignKey("MemberId")]
    [InverseProperty("UsedBooks")]
    public virtual Member Member { get; set; }

    [InverseProperty("Book")]
    public virtual ICollection<UsedBooksCart> UsedBooksCarts { get; set; } = new List<UsedBooksCart>();

    [InverseProperty("Book")]
    public virtual ICollection<UsedBooksOrderDetail> UsedBooksOrderDetails { get; set; } = new List<UsedBooksOrderDetail>();
}