// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

[Table("UsedBooksCart")]
public partial class UsedBooksCart
{
    [Key]
    public int Id { get; set; }

    public int MemberID { get; set; }

    public int BookID { get; set; }

    public DateTime AddToCartDate { get; set; }

    [ForeignKey("BookID")]
    [InverseProperty("UsedBooksCarts")]
    public virtual UsedBook Book { get; set; }

    [ForeignKey("MemberID")]
    [InverseProperty("UsedBooksCarts")]
    public virtual Member Member { get; set; }
}