// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace BackendForFrontend.Models.EFModels;

public partial class WriteBookReview
{
    [Key]
    public int ID { get; set; }

    public int MemberID { get; set; }

    public int BookID { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ReviewDate { get; set; }

    [Required]
    public string ReviewContent { get; set; }

    public int ReviewRating { get; set; }

    [ForeignKey("BookID")]
    [InverseProperty("WriteBookReviews")]
    public virtual Product Book { get; set; }

    [ForeignKey("MemberID")]
    [InverseProperty("WriteBookReviews")]
    public virtual Member Member { get; set; }
}